/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// The generated route registrations below use `as any` to bridge TanStack Router's generated route types.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyReviewRouteImport } from './routes/weekly-review'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as LogRouteImport } from './routes/log'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WeeklyReviewRoute = WeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-quality': typeof DataQualityRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/locations': typeof LocationsRoute
  '/log': typeof LogRoute
  '/manage': typeof ManageRoute
  '/methods': typeof MethodsRoute
  '/plan': typeof PlanRoute
  '/programmes': typeof ProgrammesRoute
  '/progress': typeof ProgressRoute
  '/rotation': typeof RotationRoute
  '/weekly-review': typeof WeeklyReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-quality': typeof DataQualityRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/locations': typeof LocationsRoute
  '/log': typeof LogRoute
  '/manage': typeof ManageRoute
  '/methods': typeof MethodsRoute
  '/plan': typeof PlanRoute
  '/programmes': typeof ProgrammesRoute
  '/progress': typeof ProgressRoute
  '/rotation': typeof RotationRoute
  '/weekly-review': typeof WeeklyReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-quality': typeof DataQualityRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/locations': typeof LocationsRoute
  '/log': typeof LogRoute
  '/manage': typeof ManageRoute
  '/methods': typeof MethodsRoute
  '/plan': typeof PlanRoute
  '/programmes': typeof ProgrammesRoute
  '/progress': typeof ProgressRoute
  '/rotation': typeof RotationRoute
  '/weekly-review': typeof WeeklyReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/data-quality'
    | '/goals'
    | '/history'
    | '/library'
    | '/locations'
    | '/log'
    | '/manage'
    | '/methods'
    | '/plan'
    | '/programmes'
    | '/progress'
    | '/rotation'
    | '/weekly-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-quality'
    | '/goals'
    | '/history'
    | '/library'
    | '/locations'
    | '/log'
    | '/manage'
    | '/methods'
    | '/plan'
    | '/programmes'
    | '/progress'
    | '/rotation'
    | '/weekly-review'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/data-quality'
    | '/goals'
    | '/history'
    | '/library'
    | '/locations'
    | '/log'
    | '/manage'
    | '/methods'
    | '/plan'
    | '/programmes'
    | '/progress'
    | '/rotation'
    | '/weekly-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DataQualityRoute: typeof DataQualityRoute
  GoalsRoute: typeof GoalsRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  LocationsRoute: typeof LocationsRoute
  LogRoute: typeof LogRoute
  ManageRoute: typeof ManageRoute
  MethodsRoute: typeof MethodsRoute
  PlanRoute: typeof PlanRoute
  ProgrammesRoute: typeof ProgrammesRoute
  ProgressRoute: typeof ProgressRoute
  RotationRoute: typeof RotationRoute
  WeeklyReviewRoute: typeof WeeklyReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-review': {
      id: '/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof WeeklyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DataQualityRoute: DataQualityRoute,
  GoalsRoute: GoalsRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  LocationsRoute: LocationsRoute,
  LogRoute: LogRoute,
  ManageRoute: ManageRoute,
  MethodsRoute: MethodsRoute,
  PlanRoute: PlanRoute,
  ProgrammesRoute: ProgrammesRoute,
  ProgressRoute: ProgressRoute,
  RotationRoute: RotationRoute,
  WeeklyReviewRoute: WeeklyReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
