-- Additive data-quality foundations. Historical cleanup is intentionally kept
-- in a separate approval-gated migration.

create table if not exists public.exercise_aliases (
  id uuid primary key default gen_random_uuid(),
  alias_name text not null,
  normalized_alias text generated always as (
    regexp_replace(lower(btrim(alias_name)), '[^a-z0-9]+', '', 'g')
  ) stored,
  exercise_id uuid not null references public.exercises(id) on delete cascade,
  activity_type_id uuid references public.activity_types(id) on delete cascade,
  status text not null default 'reviewed'
    check (status in ('reviewed', 'deprecated', 'manual_review')),
  reason text,
  reviewed_by uuid references public.people(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(btrim(alias_name)) > 0),
  check (length(normalized_alias) > 0)
);

create unique index if not exists exercise_aliases_global_uidx
  on public.exercise_aliases (normalized_alias)
  where activity_type_id is null and status = 'reviewed';

create unique index if not exists exercise_aliases_activity_uidx
  on public.exercise_aliases (normalized_alias, activity_type_id)
  where activity_type_id is not null and status = 'reviewed';

create index if not exists exercise_aliases_exercise_idx
  on public.exercise_aliases (exercise_id);

drop trigger if exists exercise_aliases_set_updated_at on public.exercise_aliases;
create trigger exercise_aliases_set_updated_at
before update on public.exercise_aliases
for each row execute function public.set_updated_at();

create table if not exists public.data_quality_batches (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null references public.people(id) on delete cascade,
  batch_kind text not null,
  status text not null default 'planned'
    check (status in ('planned', 'applied', 'reversed', 'failed')),
  approved_checksum text,
  applied_checksum text,
  notes text,
  created_by uuid references public.people(id) on delete set null,
  created_at timestamptz not null default now(),
  applied_at timestamptz,
  reversed_at timestamptz
);

create index if not exists data_quality_batches_person_created_idx
  on public.data_quality_batches (person_id, created_at desc);

create table if not exists public.data_quality_audit_events (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.data_quality_batches(id) on delete restrict,
  person_id uuid not null references public.people(id) on delete cascade,
  entity_table text not null,
  entity_id text not null,
  action text not null check (action in ('insert', 'update', 'move', 'delete', 'restore')),
  before_value jsonb,
  after_value jsonb,
  reason text not null,
  reversal_value jsonb,
  created_at timestamptz not null default now()
);

create index if not exists data_quality_audit_events_batch_idx
  on public.data_quality_audit_events (batch_id, id);

create index if not exists data_quality_audit_events_entity_idx
  on public.data_quality_audit_events (entity_table, entity_id);

alter table public.entry_sets
  add column if not exists data_shape text not null default 'unknown',
  add column if not exists aggregate_set_count integer,
  add column if not exists load_semantics text not null default 'unknown',
  add column if not exists volume_status text not null default 'unknown',
  add column if not exists implement_count integer;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.entry_sets'::regclass
      and conname = 'entry_sets_data_shape_check'
  ) then
    alter table public.entry_sets
      add constraint entry_sets_data_shape_check
      check (data_shape in ('individual', 'aggregate', 'unknown'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.entry_sets'::regclass
      and conname = 'entry_sets_aggregate_count_check'
  ) then
    alter table public.entry_sets
      add constraint entry_sets_aggregate_count_check
      check (
        (data_shape = 'aggregate' and aggregate_set_count is not null and aggregate_set_count > 0)
        or (data_shape <> 'aggregate' and aggregate_set_count is null)
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.entry_sets'::regclass
      and conname = 'entry_sets_load_semantics_check'
  ) then
    alter table public.entry_sets
      add constraint entry_sets_load_semantics_check
      check (
        load_semantics in (
          'total_external_load',
          'per_implement_load',
          'combined_implement_load',
          'added_bodyweight_load',
          'assistance',
          'bodyweight_contribution',
          'none',
          'unknown'
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.entry_sets'::regclass
      and conname = 'entry_sets_volume_status_check'
  ) then
    alter table public.entry_sets
      add constraint entry_sets_volume_status_check
      check (volume_status in ('exact', 'ambiguous', 'not_applicable', 'unknown'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.entry_sets'::regclass
      and conname = 'entry_sets_implement_count_check'
  ) then
    alter table public.entry_sets
      add constraint entry_sets_implement_count_check
      check (
        (load_semantics = 'per_implement_load' and implement_count is not null and implement_count > 0)
        or (load_semantics <> 'per_implement_load' and implement_count is null)
      );
  end if;
end
$$;

insert into public.activity_types (name, slug, sort_order)
values ('Mixed Training', 'mixed-training', 95)
on conflict (slug) do update
set name = excluded.name;

create or replace function app_private.validate_exercise_activity_pair()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_activity_type_id uuid;
  v_is_active boolean;
begin
  if new.exercise_id is null then
    return new;
  end if;

  select activity_type_id, is_active
  into v_activity_type_id, v_is_active
  from public.exercises
  where id = new.exercise_id;

  if not coalesce(v_is_active, false)
    or v_activity_type_id is distinct from new.activity_type_id
  then
    raise exception 'A movement references an invalid exercise or activity pairing.'
      using errcode = '23514';
  end if;
  return new;
end
$$;

drop trigger if exists session_entries_validate_exercise_activity
  on public.session_entries;
create trigger session_entries_validate_exercise_activity
before insert or update of exercise_id, activity_type_id
on public.session_entries
for each row execute function app_private.validate_exercise_activity_pair();

create or replace function app_private.validate_reviewed_exercise_alias()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.status = 'reviewed'
    and not exists (
      select 1 from public.exercises
      where id = new.exercise_id and is_active
    )
  then
    raise exception 'A reviewed alias must target an active exercise.'
      using errcode = '23514';
  end if;
  return new;
end
$$;

drop trigger if exists exercise_aliases_validate_reviewed_target
  on public.exercise_aliases;
create trigger exercise_aliases_validate_reviewed_target
before insert or update of exercise_id, status
on public.exercise_aliases
for each row execute function app_private.validate_reviewed_exercise_alias();

alter table public.person_exercises
  add column if not exists is_quick_log boolean not null default false,
  add column if not exists quick_log_order integer;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.person_exercises'::regclass
      and conname = 'person_exercises_quick_log_order_check'
  ) then
    alter table public.person_exercises
      add constraint person_exercises_quick_log_order_check
      check (
        (is_quick_log and quick_log_order is not null and quick_log_order >= 0)
        or (not is_quick_log and quick_log_order is null)
      );
  end if;
end
$$;

create unique index if not exists person_exercises_quick_log_order_uidx
  on public.person_exercises (person_id, quick_log_order)
  where is_quick_log;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.session_entries'::regclass
      and conname = 'session_entries_activity_type_present'
  ) then
    alter table public.session_entries
      add constraint session_entries_activity_type_present
      check (activity_type_id is not null) not valid;
  end if;
end
$$;

alter table public.session_entries
  validate constraint session_entries_activity_type_present;

alter table public.session_entries
  alter column activity_type_id set not null;

insert into public.exercise_tags (name, slug)
values
  ('Squat pattern', 'pattern:squat'),
  ('Hinge pattern', 'pattern:hinge'),
  ('Unilateral legs pattern', 'pattern:unilateral-legs'),
  ('Horizontal push pattern', 'pattern:horizontal-push'),
  ('Horizontal pull pattern', 'pattern:horizontal-pull'),
  ('Vertical push pattern', 'pattern:vertical-push'),
  ('Vertical pull pattern', 'pattern:vertical-pull'),
  ('Fingers and grip exposure', 'tissue:fingers-grip'),
  ('Elbows and biceps exposure', 'tissue:elbows-biceps'),
  ('Shoulders exposure', 'tissue:shoulders')
on conflict (slug) do update
set name = excluded.name;

alter table public.exercise_aliases enable row level security;
alter table public.data_quality_batches enable row level security;
alter table public.data_quality_audit_events enable row level security;

drop policy if exists exercise_aliases_select_authenticated on public.exercise_aliases;
create policy exercise_aliases_select_authenticated
  on public.exercise_aliases
  for select
  to authenticated
  using (true);

drop policy if exists exercise_aliases_insert_admin on public.exercise_aliases;
create policy exercise_aliases_insert_admin
  on public.exercise_aliases
  for insert
  to authenticated
  with check (app_private.current_person_is_admin());

drop policy if exists exercise_aliases_update_admin on public.exercise_aliases;
create policy exercise_aliases_update_admin
  on public.exercise_aliases
  for update
  to authenticated
  using (app_private.current_person_is_admin())
  with check (app_private.current_person_is_admin());

drop policy if exists exercise_aliases_delete_admin on public.exercise_aliases;
create policy exercise_aliases_delete_admin
  on public.exercise_aliases
  for delete
  to authenticated
  using (app_private.current_person_is_admin());

drop policy if exists data_quality_batches_select_managed on public.data_quality_batches;
create policy data_quality_batches_select_managed
  on public.data_quality_batches
  for select
  to authenticated
  using (app_private.person_is_accessible(person_id));

drop policy if exists data_quality_audit_events_select_managed
  on public.data_quality_audit_events;
create policy data_quality_audit_events_select_managed
  on public.data_quality_audit_events
  for select
  to authenticated
  using (app_private.person_is_accessible(person_id));

drop policy if exists exercise_tags_insert_admin on public.exercise_tags;
create policy exercise_tags_insert_admin
  on public.exercise_tags
  for insert
  to authenticated
  with check (app_private.current_person_is_admin());

drop policy if exists exercise_tags_update_admin on public.exercise_tags;
create policy exercise_tags_update_admin
  on public.exercise_tags
  for update
  to authenticated
  using (app_private.current_person_is_admin())
  with check (app_private.current_person_is_admin());

drop policy if exists exercise_tags_delete_admin on public.exercise_tags;
create policy exercise_tags_delete_admin
  on public.exercise_tags
  for delete
  to authenticated
  using (app_private.current_person_is_admin());

drop policy if exists exercise_tag_links_insert_admin on public.exercise_tag_links;
create policy exercise_tag_links_insert_admin
  on public.exercise_tag_links
  for insert
  to authenticated
  with check (app_private.current_person_is_admin());

drop policy if exists exercise_tag_links_delete_admin on public.exercise_tag_links;
create policy exercise_tag_links_delete_admin
  on public.exercise_tag_links
  for delete
  to authenticated
  using (app_private.current_person_is_admin());

grant select, insert, update, delete on table public.exercise_aliases to authenticated;
grant select on table public.data_quality_batches to authenticated;
grant select on table public.data_quality_audit_events to authenticated;
grant insert, update, delete on table public.exercise_tags to authenticated;
grant insert, delete on table public.exercise_tag_links to authenticated;
grant usage, select on sequence public.data_quality_audit_events_id_seq to authenticated;

create or replace function public.save_workout(
  p_person_id uuid,
  p_session jsonb,
  p_entries jsonb,
  p_method_blocks jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_session_id uuid;
  v_entry_id uuid;
  v_set_id uuid;
  v_block_id uuid;
  v_entry jsonb;
  v_set jsonb;
  v_metric jsonb;
  v_segment jsonb;
  v_block jsonb;
  v_member jsonb;
  v_entry_ids jsonb := '{}'::jsonb;
  v_client_id text;
  v_activity_type_id uuid;
  v_exercise_id uuid;
  v_parent_activity_type_id uuid;
  v_completed boolean := coalesce((p_session->>'completed')::boolean, true);
begin
  if not app_private.person_is_accessible(p_person_id) then
    raise exception 'The requested training profile is not accessible.'
      using errcode = '42501';
  end if;

  if jsonb_typeof(p_entries) <> 'array' or jsonb_array_length(p_entries) = 0 then
    raise exception 'A workout requires at least one movement.'
      using errcode = '22023';
  end if;

  insert into public.sessions (
    person_id,
    activity_type_id,
    session_date,
    title,
    source,
    completed,
    duration_minutes,
    intensity,
    rpe,
    notes,
    training_location_id,
    source_sheet,
    source_row
  )
  values (
    p_person_id,
    nullif(p_session->>'activity_type_id', '')::uuid,
    (p_session->>'session_date')::date,
    nullif(btrim(p_session->>'title'), ''),
    'manual',
    false,
    nullif(p_session->>'duration_minutes', '')::numeric,
    nullif(p_session->>'intensity', ''),
    nullif(p_session->>'rpe', '')::numeric,
    nullif(p_session->>'notes', ''),
    nullif(p_session->>'training_location_id', '')::uuid,
    null,
    null
  )
  returning id into v_session_id;

  for v_entry in select value from jsonb_array_elements(p_entries)
  loop
    v_activity_type_id := nullif(v_entry->>'activity_type_id', '')::uuid;
    v_exercise_id := nullif(v_entry->>'exercise_id', '')::uuid;
    v_client_id := nullif(v_entry->>'client_id', '');

    if v_activity_type_id is null
      or not exists (
        select 1 from public.activity_types where id = v_activity_type_id
      )
    then
      raise exception 'Every movement requires a valid activity type.'
        using errcode = '22023';
    end if;

    if v_exercise_id is not null and not exists (
      select 1
      from public.exercises
      where id = v_exercise_id
        and is_active
        and (activity_type_id is null or activity_type_id = v_activity_type_id)
    ) then
      raise exception 'A movement references an invalid exercise or activity pairing.'
        using errcode = '22023';
    end if;

    insert into public.session_entries (
      session_id,
      exercise_id,
      activity_type_id,
      entry_kind,
      name,
      progression_level,
      order_index,
      completed,
      notes,
      source_sheet,
      source_row
    )
    values (
      v_session_id,
      v_exercise_id,
      v_activity_type_id,
      nullif(v_entry->>'entry_kind', ''),
      btrim(v_entry->>'name'),
      nullif(v_entry->>'progression_level', ''),
      coalesce((v_entry->>'order_index')::integer, 0),
      coalesce((v_entry->>'completed')::boolean, true),
      nullif(v_entry->>'notes', ''),
      null,
      null
    )
    returning id into v_entry_id;

    if v_client_id is not null then
      v_entry_ids := v_entry_ids || jsonb_build_object(v_client_id, v_entry_id::text);
    end if;

    for v_set in
      select value from jsonb_array_elements(coalesce(v_entry->'sets', '[]'::jsonb))
    loop
      insert into public.entry_sets (
        session_entry_id,
        set_number,
        reps,
        weight,
        duration_seconds,
        distance,
        distance_unit,
        rpe,
        rest_time,
        assistance_type,
        assistance_detail,
        quality,
        completed,
        notes,
        data_shape,
        aggregate_set_count,
        load_semantics,
        volume_status,
        implement_count
      )
      values (
        v_entry_id,
        nullif(v_set->>'set_number', '')::integer,
        nullif(v_set->>'reps', '')::numeric,
        nullif(v_set->>'weight', '')::numeric,
        nullif(v_set->>'duration_seconds', '')::numeric,
        nullif(v_set->>'distance', '')::numeric,
        nullif(v_set->>'distance_unit', ''),
        nullif(v_set->>'rpe', '')::numeric,
        nullif(v_set->>'rest_time', ''),
        nullif(v_set->>'assistance_type', ''),
        nullif(v_set->>'assistance_detail', ''),
        nullif(v_set->>'quality', ''),
        coalesce((v_set->>'completed')::boolean, true),
        nullif(v_set->>'notes', ''),
        coalesce(nullif(v_set->>'data_shape', ''), 'individual'),
        nullif(v_set->>'aggregate_set_count', '')::integer,
        coalesce(nullif(v_set->>'load_semantics', ''), 'unknown'),
        coalesce(nullif(v_set->>'volume_status', ''), 'unknown'),
        nullif(v_set->>'implement_count', '')::integer
      )
      returning id into v_set_id;

      for v_segment in
        select value from jsonb_array_elements(coalesce(v_set->'segments', '[]'::jsonb))
      loop
        insert into public.entry_set_segments (
          entry_set_id,
          training_method_id,
          method_name,
          segment_index,
          reps,
          weight,
          rpe,
          rest_after_seconds,
          range_of_motion,
          config
        )
        values (
          v_set_id,
          (v_segment->>'training_method_id')::uuid,
          v_segment->>'method_name',
          coalesce((v_segment->>'segment_index')::integer, 0),
          nullif(v_segment->>'reps', '')::numeric,
          nullif(v_segment->>'weight', '')::numeric,
          nullif(v_segment->>'rpe', '')::numeric,
          nullif(v_segment->>'rest_after_seconds', '')::integer,
          nullif(v_segment->>'range_of_motion', ''),
          coalesce(v_segment->'config', '{}'::jsonb)
        );
      end loop;
    end loop;

    for v_metric in
      select value from jsonb_array_elements(coalesce(v_entry->'metrics', '[]'::jsonb))
    loop
      insert into public.entry_metrics (
        session_entry_id,
        metric_key,
        metric_value,
        metric_text,
        metric_unit
      )
      values (
        v_entry_id,
        v_metric->>'metric_key',
        nullif(v_metric->>'metric_value', '')::numeric,
        nullif(v_metric->>'metric_text', ''),
        nullif(v_metric->>'metric_unit', '')
      );
    end loop;
  end loop;

  for v_block in
    select value from jsonb_array_elements(coalesce(p_method_blocks, '[]'::jsonb))
  loop
    insert into public.session_method_blocks (
      session_id,
      training_method_id,
      method_name,
      family,
      order_index,
      rounds,
      rest_between_movements_seconds,
      rest_between_rounds_seconds,
      block_duration_seconds,
      work_interval_seconds,
      rest_interval_seconds,
      completed_rounds,
      config
    )
    values (
      v_session_id,
      (v_block->>'training_method_id')::uuid,
      v_block->>'method_name',
      v_block->>'family',
      coalesce((v_block->>'order_index')::integer, 0),
      nullif(v_block->>'rounds', '')::integer,
      nullif(v_block->>'rest_between_movements_seconds', '')::integer,
      nullif(v_block->>'rest_between_rounds_seconds', '')::integer,
      nullif(v_block->>'block_duration_seconds', '')::integer,
      nullif(v_block->>'work_interval_seconds', '')::integer,
      nullif(v_block->>'rest_interval_seconds', '')::integer,
      nullif(v_block->>'completed_rounds', '')::integer,
      coalesce(v_block->'config', '{}'::jsonb)
    )
    returning id into v_block_id;

    for v_member in
      select value from jsonb_array_elements(coalesce(v_block->'member_client_ids', '[]'::jsonb))
    loop
      if not (v_entry_ids ? (v_member #>> '{}')) then
        raise exception 'A training-method block references an unknown movement.'
          using errcode = '22023';
      end if;

      insert into public.session_method_block_entries (
        block_id,
        session_entry_id,
        sequence_index
      )
      values (
        v_block_id,
        (v_entry_ids->>(v_member #>> '{}'))::uuid,
        coalesce((
          select count(*)::integer
          from public.session_method_block_entries
          where block_id = v_block_id
        ), 0)
      );
    end loop;
  end loop;

  select
    case
      when count(distinct activity_type_id) = 1 then min(activity_type_id::text)::uuid
      else (
        select id from public.activity_types where slug = 'mixed-training'
      )
    end
  into v_parent_activity_type_id
  from public.session_entries
  where session_id = v_session_id;

  update public.sessions
  set
    activity_type_id = v_parent_activity_type_id,
    completed = v_completed
  where id = v_session_id;

  return v_session_id;
end
$$;

revoke all on function public.save_workout(uuid, jsonb, jsonb, jsonb)
  from public, anon;
grant execute on function public.save_workout(uuid, jsonb, jsonb, jsonb)
  to authenticated;
